version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: sharepains
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
  es01:
    image: elasticsearch:6.8.3
    container_name: elasticsearch01
    ports:
      - "9200:9200"
    volumes:
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=node01
      # JVMのメモリを指定する。指定しないとメモリが足らなかった。。。
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    expose:
      - "9200"
  es02:
    image: elasticsearch:6.8.3
    container_name: elasticsearch02
    ports:
      - "9201:9200"
    volumes:
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=node02
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  es03:
    image: elasticsearch:6.8.3
    container_name: elasticsearch03
    ports:
      - "9202:9200"
    volumes:
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=node03
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    ports:
      - "9001:9000"
    restart: always
#  kibana:
#    image:  docker.elastic.co/kibana/kibana:6.8.3
#    ports:
#      - "5601:5601"

